# Generated by Django 4.2.6 on 2023-10-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0005_account_created_by_google'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('times_used', models.IntegerField()),
            ],
        ),
    ]
