# Generated by Django 4.2.6 on 2023-11-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rodManager", "0006_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Garden",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("sector", models.CharField(blank=True, max_length=255, null=True)),
                ("avenue", models.CharField(blank=True, max_length=255, null=True)),
                ("number", models.IntegerField()),
                ("area", models.FloatField(blank=True, null=True)),
                (
                    "leaseholderID",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dostepna", "Available"),
                            ("niedostepna", "Unavailable"),
                        ],
                        default="dostepna",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
