# Generated by Django 4.2.6 on 2023-11-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0006_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('images', models.ManyToManyField(blank=True, to='rodManager.image')),
                ('tags', models.ManyToManyField(blank=True, to='rodManager.tag')),
            ],
        ),
    ]
