# Generated by Django 4.2.6 on 2023-11-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0007_alter_image_image_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
