# Generated by Django 4.2.6 on 2023-11-14 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0009_alter_announcement_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rodManager.announcement')),
            ],
        ),
    ]
