# Generated by Django 4.2.6 on 2023-11-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0011_garden_gardenoffers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='status',
            field=models.CharField(choices=[('dostepna', 'Available'), ('niedostepna', 'Unavailable')], default='dostepna', max_length=20),
        ),
    ]
