# Generated by Django 4.2.6 on 2023-11-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0007_garden'),
        ('rodManager', '0012_alter_garden_status'),
    ]

    operations = [
    ]
