# Generated by Django 4.2.6 on 2023-11-28 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rodManager", "0013_merge_0007_garden_0012_alter_garden_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leaseholderID", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("amount", models.FloatField()),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(model_name="garden", name="status",),
        migrations.AddField(
            model_name="garden",
            name="last_leaseholder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="last_leaseholder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="garden",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="garden",
            name="leaseholderID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
