# Generated by Django 4.2.6 on 2023-12-01 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "rodManager",
            "0014_payment_remove_garden_status_garden_last_leaseholder_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Meter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=200)),
                ("adress", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("value", models.FloatField()),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rodManager.meter",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Payment",),
        migrations.AddField(
            model_name="garden",
            name="status",
            field=models.CharField(
                choices=[("dostepna", "Available"), ("niedostepna", "Unavailable")],
                default="dostepna",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="meter",
            name="garden",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meters",
                to="rodManager.garden",
            ),
        ),
    ]
