# Generated by Django 4.2.6 on 2023-11-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0014_payment_remove_garden_status_garden_last_leaseholder_and_more'),
        ('rodManager', '0015_rename_title_document_name_remove_document_uuid'),
    ]

    operations = [
    ]
