# Generated by Django 4.2.6 on 2023-12-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0015_meter_record_delete_payment_garden_status_and_more'),
        ('rodManager', '0016_merge_20231129_1909'),
    ]

    operations = [
    ]
