# Generated by Django 4.2.6 on 2023-12-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0017_option_pool_vote_delete_payment_option_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='status',
            field=models.CharField(choices=[('dostepna', 'Available'), ('niedostepna', 'Unavailable')], default='dostepna', max_length=20),
        ),
    ]
