# Generated by Django 4.2.6 on 2023-12-02 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "rodManager",
            "0018_option_poll_vote_remove_record_meter_delete_meter_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("opening_date", models.DateTimeField(auto_now_add=True)),
                ("closing_date", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Reported", "Zgłoszono"),
                            ("Accepted", "Przyjęto"),
                            ("InProgress", "W trakcie"),
                            ("Complete", "Zakończono"),
                            ("Rejected", "Odrzucono"),
                        ],
                        default="Reported",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        choices=[("USER", "Użytkownik"), ("MANAGER", "Zarządca")],
                        default="USER",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="rodManager.complaint",
                    ),
                ),
            ],
        ),
    ]
