# Generated by Django 4.2.6 on 2023-12-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rodManager", "0019_complaint_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="complaint",
            old_name="closing_date",
            new_name="close_date",
        ),
        migrations.RenameField(
            model_name="complaint",
            old_name="opening_date",
            new_name="open_date",
        ),
    ]
