# Generated by Django 4.2.6 on 2023-12-05 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0020_rename_closing_date_complaint_close_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
