# Generated by Django 4.2.6 on 2023-12-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0021_complaint_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
    ]
