# Generated by Django 4.2.6 on 2023-12-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rodManager", "0023_fee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billingperiod",
            old_name="is_closed",
            new_name="is_confirmed",
        ),
    ]
