# Generated by Django 4.2.6 on 2023-12-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0026_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RodDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='roddocuments/')),
            ],
        ),
    ]
