# Generated by Django 4.2.6 on 2023-12-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0028_userdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingperiod',
            name='confimation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='un_read_user',
            field=models.CharField(choices=[('USER', 'Użytkownik'), ('MANAGER', 'Zarządca')], default='MANAGER', max_length=20, null=True),
        ),
    ]
