# Generated by Django 4.2.6 on 2023-12-13 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0029_billingperiod_confimation_date_and_more'),
        ('rodManager', '0029_meter_record'),
    ]

    operations = [
    ]
