# Generated by Django 4.2.6 on 2023-12-13 22:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0031_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RODGardens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RODDescription', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='time',
        ),
        migrations.AddField(
            model_name='record',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meter',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rodManager.garden'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('BillPayment', 'Billpayment'), ('Correction', 'Correction'), ('Payment', 'Payment'), ('Individual', 'Individual')], default='Payment', max_length=20),
        ),
    ]
