# Generated by Django 4.2.6 on 2023-12-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0032_employee_rodgardens_remove_record_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingperiod',
            old_name='confimation_date',
            new_name='confirmation_date',
        ),
    ]
