version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/
    env_file:
      - ./.env.dev
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3308:3306"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./mediafiles:/home/app/web/mediafiles
    ports:
      - 1337:1337
    depends_on:
      - web
  angular-app:
    build:
      context: ./rod-manager-ui
      dockerfile: Dockerfile
    ports:
      - "4200:80"  # Expose port 4200 (or any other port you wish to use)
    depends_on:
      - web # Replace with the name of your Django service

volumes:
  mariadb_data:
  media_volume:
